from .config import (
    AWS_REGION,
    LOGIN_TABLE,
    MUSIC_TABLE,
    MUSIC_TITLE_GSI,
    MUSIC_YEAR_LSI,
    S3_BUCKET,
    S3_PRESIGN_TTL,
    SESSION_SECRET,
    SESSION_TTL_SECONDS,
    LAB_ROLE_NAME,
)
